#!/bin/bash

export FLOR_ROBOT_TYPE="atlas_v5" 
export FLOR_LEFT_HAND_TYPE="l_stump" 
export FLOR_RIGHT_HAND_TYPE="r_stump"
export VIGIR_LEFT_GUARD_TYPE="l_no_guard"
export VIGIR_RIGHT_GUARD_TYPE="r_no_guard"

echo "Set up for the ATLAS robot ..."
echo "  Robot type = "$FLOR_ROBOT_TYPE
echo "  Left hand type = "$FLOR_LEFT_HAND_TYPE
echo "  Right hand type = "$FLOR_RIGHT_HAND_TYPE
echo "  Left guard type = "$VIGIR_LEFT_GUARD_TYPE
echo "  Right guard type = "$VIGIR_RIGHT_GUARD_TYPE
. atlas_multisense

