#!/bin/bash -e

# Search the experiment results directory for any uncompressed bag files and 
# compresses them.
# There must not be any white spaces in the path
#
# Useage:
# vigir
# cd scripts
# ./bag_compress_recursive /path/to/bag-files
#   [version] describes the Atlas version (3,4,5)

# Moritz Schappler, schappler@irt.uni-hannover.de, 2015-04
# (c) Institut für Regelungstechnik, Universität Hannover

# Check Input
if [ ! -d "$1" ]; then
  echo "Directory "$1" does not exist."
  exit
fi

# Loop through all bag files
for f in $(find $1/ -name '*.bag') # find all bag files
do
  filename=$(basename "$f")
  filename="${filename%.*}" # gets filename without path and extension
  pathtofile=$(dirname "$f") # gets directory of the file

  filepath_bag="$pathtofile/${filename}.bag"
  filepath_backup="$pathtofile/${filename}.orig.bag"

  # check if bag file compression necessary
  if [ $(rosbag info $f | grep "compression: none"  | wc -l) == "1" ]; then
    echo "bag-file $filepath_bag is uncompressed. Compressing data"
    nice rosbag compress "$f"
    # delete uncompressed file
    rm -f "$filepath_backup"
  fi 
done

