#!/bin/bash

DRCSIM_VERSION="3.1"
DRCSIM_SHARE="/usr/share/drcsim"

# check if the drcsim directory exists
if [ ! -d $DRCSIM_SHARE ]; then
    echo "Error: drcsim-$DRCSIM_VERSION share directory not found at: $DRCSIM_SHARE"
    return 1
fi

echo "Adding drcsim-$DRCSIM_VERSION models ..."
# Step 2: modify ROS configuration.
# Add each of our installed model directories to ROS_PACKAGE_PATH, so that ROS tools can locate resources stored within them.
# We don't just add the top 'models' directory because it contains a 'manifest.xml', which stops rospack in its tracks.
for SUBDIR in environments atlas_description multisense_sl_description irobot_hand_description; do
    for PACKAGE_PATH in `find $DRCSIM_SHARE/gazebo_models/$SUBDIR -mindepth 1 -maxdepth 1 -type d`; do
        export ROS_PACKAGE_PATH=$PACKAGE_PATH:$ROS_PACKAGE_PATH;
    done
done


# Also add our 'ros' directory to RPP; it contains utility packages with things like launch files
export ROS_PACKAGE_PATH=/usr/share/sandia-hand-5.1/ros:$DRCSIM_SHARE/ros:$ROS_PACKAGE_PATH
export ROS_PACKAGE_PATH=/usr/share/osrf-common-1.0/ros:$ROS_PACKAGE_PATH
