#!/bin/bash

export VIGIR_LEFT_GUARD_TYPE="l_no_guard"
export VIGIR_RIGHT_GUARD_TYPE="r_no_guard"

echo "  Left guard type = "$VIGIR_LEFT_GUARD_TYPE
echo "  Right guard type = "$VIGIR_RIGHT_GUARD_TYPE
