#!/bin/bash

if [ "$HOSTNAME" = legolas ]; then

    echo "Tried to kill camera_sensors"
    screen -x  camera_sensors -X quit

    echo "Tried to kill perception"
    screen -x  perception     -X quit

    if [ "$1" != "no_comms" ]; then
        echo "Tried to kill comms_bridge"
        screen -x  comms_bridge   -X quit
    else
        echo "Did not kill comms_bridge"
    fi

    echo "Anyone still out there?"
    screen -ls

else

    echo "Please run from legolas"

fi
