#!/bin/bash

CLEAN=false
if [ -z $1 ]
  then
    echo "Provide controller name and joint name as arguments, e.g."
    echo "plot_traj_control_data left_arm 4"
    exit 1
fi

rqt_plot topics /flor/controller/atlas_state/position[$1] /flor/controller/joint_command/position[$1] &
rqt_plot topics /flor/controller/atlas_state/velocity[$1] /flor/controller/joint_command/velocity[$1] &
rqt_plot topics /flor/controller/atlas_state/effort[$1] /flor/controller/joint_command/effort[$1] &
rqt_plot topics /flor/controller/joint_command/acceleration[$1] &
rqt_plot topics /flor/controller/joint_command/ff_const[$1] &



