#!/bin/bash

if [ "$HOSTNAME" = legolas ]; then

    echo "Stopping any old startups"
    killall_legolas "$1"

    echo "Setting Network"

    if [ $(ifconfig eth1 | grep inet | grep -v inet6 | awk '{print $2}') != 'addr:10.66.171.102' ]; then
        robot_eth1
    fi

    if [ $(ifconfig eth0 | grep inet | grep -v inet6 | awk '{print $2}') != 'addr:172.24.21.6' ]; then
        field_eth0
    fi

    if ! rostopic list &>/dev/null; then
        echo "Conner, you idiot, start ROS"
        exit
    fi

    PS1='$ '
    source ~/.bashrc

    screen  -S camera_sensors -d -m /bin/bash -ic "roslaunch flor_atlas_bringup camera_sensors.launch; bash"
    echo "Started camera_sensors screen"

    screen  -S perception     -d -m /bin/bash -ic "roslaunch vigir_onboard perception.launch; bash"
    echo "Started perception screen"

    if [ "$1" != "no_comms" ]; then
        screen  -S comms_bridge   -d -m /bin/bash -ic "roslaunch vigir_comms_bridge field_bridge_legolas.launch; bash"
        echo "Started comms_bridge screen"
    else
        echo "Start comms bridge screen to the the image topic relay instead of true comms_bridge "
        screen  -S comms_bridge   -d -m /bin/bash -ic "roslaunch vigir_image_processing relay_crop_decimate_without_comms_bridge.launch; bash"
    fi

    screen -ls

else

    echo "Please run from legolas"

fi
