#!/bin/bash

computers=( frodo aragorn legolas sam )

for computer in ${computers[*]}; do
    echo "Resetting processes on $computer"
    ssh $computer"_field" "killall_$computer \"$1\""
    ssh $computer"_field" "startup_$computer \"$1\""
    echo""
done
