#!/bin/bash

if [ "$HOSTNAME" = aragorn ]; then

    echo "Stopping any old startups"
    killall_aragorn "$1"

    echo "Setting Network"
    
    if [ $(ifconfig eth1 | grep inet | grep -v inet6 | awk '{print $2}') != 'addr:10.66.171.101' ]; then 
        robot_eth1
    fi

    if [ $(ifconfig eth0 | grep inet | grep -v inet6 | awk '{print $2}') != 'addr:172.24.21.5' ]; then 
        field_eth0 
    fi

    if ! rostopic list &>/dev/null; then 
        echo "Conner, you idiot, start ROS"
        exit
    fi

    PS1='$ '
    source ~/.bashrc
   
         
#    screen  -S roscore -d -m /bin/bash -ic "roscore; bash"
#    echo "Started roscore screen. Waiting 6 seconds before continuing"
#
#    sleep 6 

    screen  -S basic_controller     -d -m /bin/bash -ic "roslaunch vigir_onboard_machines basic_controller_setup.launch; bash"
    echo "Started basic_controller screen"
   
    if [ "$1" != "no_comms" ]; then
        screen  -S comms_bridge   -d -m /bin/bash -ic "roslaunch vigir_comms_bridge field_bridge_aragorn.launch; bash"
        echo "Started comms_bridge screen"
    else
        echo "Did not kill comms_bridge"
    fi

    screen  -S onboard_recorder   -d -m /bin/bash -ic "roslaunch flor_bag_record onboard_basic_record.launch; bash"
    echo "Started onboard bag recorder screen"

    screen -ls
    
else

    echo "Please run from aragorn"

fi
