# Step 3: Modify LD_LIBRARY_PATH to include some unusual locations.
# Make AtlasSimInterface plugins visible to the runtime loader
export LD_LIBRARY_PATH=/opt/ros/indigo/lib/AtlasSimInterface_1.1.1:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/opt/ros/indigo/lib/AtlasSimInterface_2.10.2:$LD_LIBRARY_PATH
# Make Gazebo-ROS plugins visible to the runtime loader; they'll be
# pulled in by ROS via pluginlib
export LD_LIBRARY_PATH=/opt/ros/indigo/lib/drcsim_gazebo_ros_plugins/plugins:$LD_LIBRARY_PATH

# Step 4: get Gazebo configuration.
if [ -f /usr/share/gazebo/setup.sh ]; then
  . /usr/share/gazebo/setup.sh 
elif [ -f /usr/share/gazebo/setup.sh ]; then
  . /usr/share/gazebo/setup.sh  
else
  echo "Warning: failed to find Gazebo's setup.sh.  You will need to source it manually."
fi

# Step 5: modify Gazebo configuration.
# Add our top-level directory to GAZEBO_RESOURCE_PATH so that its
# media/materials/* stuff can be found.
export GAZEBO_RESOURCE_PATH=/opt/ros/indigo/share/drcsim_model_resources:$GAZEBO_RESOURCE_PATH
# Add our worlds directory to GAZEBO_RESOURCE_PATH so that *.world files can be
# found without giving a full path.
export GAZEBO_RESOURCE_PATH=/opt/ros/indigo/share/drcsim_model_resources/worlds:$GAZEBO_RESOURCE_PATH
# export GAZEBO_RESOURCE_PATH=/opt/ros/indigo/share/drcsim_model_resources-/worlds:$GAZEBO_RESOURCE_PATH

# add path to gazebo models from sandia_hand_description
export GAZEBO_MODEL_PATH=/opt/ros/indigo/share/sandia_hand_description:$GAZEBO_MODEL_PATH

# add path to gazebo models from irobot_hand_description
export GAZEBO_MODEL_PATH=/opt/ros/indigo/share/irobot_hand_description:$GAZEBO_MODEL_PATH

# add path to gazebo models from multisense_sl_description
export GAZEBO_MODEL_PATH=/opt/ros/indigo/share/multisense_sl_description:$GAZEBO_MODEL_PATH

# add path to gazebo models from atlas_description
export GAZEBO_MODEL_PATH=/opt/ros/indigo/share/atlas_description:$GAZEBO_MODEL_PATH

# add path to gazebo standalone models generated by atlas_description
export GAZEBO_MODEL_PATH=/opt/ros/indigo/share/drcsim_gazebo_standalone_models:$GAZEBO_MODEL_PATH

# add path to gazebo models from drcsim_model_resources
export GAZEBO_MODEL_PATH=/opt/ros/indigo/share/drcsim_model_resources/gazebo_models/environments:$GAZEBO_MODEL_PATH

# old stuff?
# export GAZEBO_MODEL_PATH=/opt/ros/indigo/share:$GAZEBO_MODEL_PATH
# export GAZEBO_MODEL_PATH=/opt/ros/indigo/share/drcsim_model_resources-/gazebo_models/environments:$GAZEBO_MODEL_PATH

# Add the directories containing our Gazebo plugins to GAZEBO_PLUGIN_PATH.
export GAZEBO_PLUGIN_PATH=/opt/ros/indigo/lib/drcsim_gazebo_ros_plugins/plugins:$GAZEBO_PLUGIN_PATH
